[mypy]
# Verwendet das installierte Django-Plugin für Mypy
plugins = mypy_django_plugin.main

# Ignoriert fehlende Type-Stubs von Drittanbieter-Paketen (z.B. pytest, dj_database_url)
ignore_missing_imports = True

[mypy.plugins.django-stubs]
# Sagt Mypy, wo deine Django-Settings liegen
django_settings_module = "core.settings"