[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "portfolio_project"
version = "0.1.0"
description = "Mein Portfolio Backend"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
    "django-cors-headers>=4.3.0",
    "django-storages[boto3]",
    "psycopg2-binary",
    "python-dotenv",
    "pillow",
    "pytest-django",
    "dj-database-url",
    "whitenoise",
    "djoser>=2.3.3",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "gunicorn>=26.1.0",
]

# Konfiguration für Mypy (löst deine Fehler-Meldungen)
[tool.mypy]
python_version = "3.13"
ignore_missing_imports = true
check_untyped_defs = true
exclude = ["^build/", "migrations/"]

# Konfiguration für Tools, die du eventuell noch nutzt
[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings_test"
python_files = ["tests.py", "test_*.py"]

[tool.coverage.run]
omit = [
    "core/asgi.py",
    "core/wsgi.py",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
extend-select = ["I", "BLE", "RUF"]

[tool.ruff.lint.per-file-ignores]
"**/migrations/*" = ["RUF012"]

[tool.djlint]
profile = "django"
ignore = "H014"

# Hier sagen wir uv/setuptools explizit, wo der Python-Code liegt
[tool.setuptools.packages.find]
include = ["core*", "portfolio*"]

[dependency-groups]
dev = [
    "djlint>=1.44.2",
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-django>=4.12.0",
    "ruff>=0.16.0",
]
