[pytest]
# Teilt Pytest mit, wo die Django-Settings liegen
DJANGO_SETTINGS_MODULE = core.settings

# Definiert die Namenskonventionen für Testdateien
python_files = tests.py test_*.py *_tests.py

# Optional: Sorgt für eine detailliertere und farbige Ausgabe im Terminal
addopts = -v --reuse-db