# Exported from Render on 2026-08-20T18:10:08Z
version: "1"
projects:
- name: MyPortfolio
  environments:
  - name: prod
    services:
    - type: web
      name: portfolio-project
      runtime: python
      repo: https://github.com/dfluechter/portfolio_project
      plan: free
      envVars:
      - key: DATABASE_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_S3_ENDPOINT_URL
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: PYTHON_VERSION
        sync: false
      region: frankfurt
      buildCommand: bash build.sh
      startCommand: gunicorn core.wsgi:application
      healthCheckPath: /health_check
      domains:
      - dfluechter.ipv64.de
      autoDeployTrigger: commit
      renderSubdomainPolicy: disabled
