# Generated by Django 6.0.7 on 2026-09-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_pendingcertificate_track_alter_provider_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Gestartet um")),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Beendet um"
                    ),
                ),
                (
                    "files_found",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dateien gefunden"
                    ),
                ),
                (
                    "files_imported",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dateien importiert"
                    ),
                ),
                (
                    "files_skipped",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dateien übersprungen"
                    ),
                ),
                (
                    "files_errored",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dateien fehlerhaft"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Läuft"),
                            ("success", "Erfolgreich"),
                            ("partial", "Teilweise erfolgreich"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("log", models.TextField(blank=True, verbose_name="Log-Protokoll")),
                (
                    "inbox_path",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="Inbox-Verzeichnis"
                    ),
                ),
            ],
            options={
                "verbose_name": "Import-Lauf",
                "verbose_name_plural": "Import-Läufe",
                "ordering": ("-started_at",),
            },
        ),
    ]
