# Generated by Django 6.0.7 on 2026-10-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_migrate_track_fk_to_m2m_and_backfill_hashes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="track",
        ),
        migrations.AlterField(
            model_name="certificate",
            name="sha256_hash",
            field=models.CharField(
                db_index=True, max_length=64, unique=True, verbose_name="SHA-256 Hash"
            ),
        ),
    ]
