# Generated by Django 6.0.7 on 2026-10-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_remove_certificate_track_fk_and_sha256_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingcertificate",
            name="certificate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_pending",
                to="portfolio.certificate",
                verbose_name="Zugeordnetes Zertifikat",
            ),
        ),
        migrations.AddField(
            model_name="pendingcertificate",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_certificates",
                to="portfolio.certificateimportrun",
                verbose_name="Import-Lauf",
            ),
        ),
        migrations.AddField(
            model_name="pendingcertificate",
            name="suggested_tracks",
            field=models.ManyToManyField(
                blank=True,
                related_name="suggested_pending_certificates",
                to="portfolio.track",
                verbose_name="Vorgeschlagene Tracks",
            ),
        ),
    ]
