# Generated by Django 5.2.15 on 2026-06-08 23:42

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel des Zertifikats')),
                ('issuer', models.CharField(max_length=255, verbose_name='Aussteller / Organisation')),
                ('pdf_file', models.FileField(upload_to=portfolio.models.certificate_upload_path, verbose_name='PDF Datei')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
            ],
            options={
                'verbose_name': 'Zertifikat',
                'verbose_name_plural': 'Zertifikate',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Projektname')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Projekt-Vorschaubild')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub Repository URL')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='Live Demo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['-created_at'],
            },
        ),
    ]
