# Generated by Django 6.0.7 on 2026-09-18 14:46

from django.db import migrations, models


def create_default_provider(apps, schema_editor):
    Provider = apps.get_model("portfolio", "Provider")
    Provider.objects.get_or_create(
        id=1, defaults={"provider": "Unsortiert (Legacy)", "aktiv": True}
    )


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Anbieter"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="provider_logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Zertifikatsanbieter",
                "verbose_name_plural": "Zertifikatsanbieter",
            },
        ),
        migrations.RunPython(create_default_provider, migrations.RunPython.noop),
    ]
