# Generated by Django 5.2.15 on 2026-06-29 10:08

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(upload_to=portfolio.models.certificate_upload_path, validators=[portfolio.models.validate_file_extension, portfolio.models.validate_file_size], verbose_name='PDF / PNG Datei'),
        ),
    ]
