# Generated by Django 6.0.7 on 2026-07-11 14:27

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_certificate_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255, unique=True, verbose_name='Anbieter')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='provider_logos/', verbose_name='Logo')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Zertifikatsanbieter',
                'verbose_name_plural': 'Zertifikatsanbieter',
            },
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(upload_to=portfolio.models.certificate_upload_path, validators=[portfolio.models.validate_file_extension, portfolio.models.validate_file_size], verbose_name='PDF / PNG / JPG Datei'),
        ),
    ]
