# Generated by Django 6.0.7 on 2026-09-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certificateimportrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='credential_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Credential-ID'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Veröffentlicht'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ausstellungsdatum'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='ocr_pending',
            field=models.BooleanField(default=False, verbose_name='OCR ausstehend'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='sha256_hash',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True, verbose_name='SHA-256 Hash'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='storage_key',
            field=models.CharField(blank=True, max_length=512, verbose_name='Storage-Objektschlüssel'),
        ),
    ]
