# Generated by Django 6.0.7 on 2026-10-02 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_certificate_credential_id_certificate_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='portfolio.track', verbose_name='Zugeordnete Tracks'),
        ),
        migrations.AddField(
            model_name='pendingcertificate',
            name='sha256_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='SHA-256 Hash'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_certificates', to='portfolio.track', verbose_name='Zugeordneter Track (Legacy)'),
        ),
    ]
